# Generated by Django 3.2.8 on 2021-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinions',
            new_name='Opinion',
        ),
        migrations.AlterField(
            model_name='shop',
            name='product_url',
            field=models.URLField(null=True),
        ),
    ]
